### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
  id: ApplicationIntegrationType
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.GuildInstallable
  - Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.UserInstallable
  langs:
  - csharp
  - vb
  name: ApplicationIntegrationType
  nameWithType: ApplicationIntegrationType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
  type: Enum
  source:
    id: ApplicationIntegrationType
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationIntegrationType.cs
    startLine: 29
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Represents valid locations for users to install application integrations.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public enum ApplicationIntegrationType
    content.vb: >-
      <PublicAPI>

      Public Enum ApplicationIntegrationType
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.GuildInstallable
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.GuildInstallable
  id: GuildInstallable
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
  langs:
  - csharp
  - vb
  name: GuildInstallable
  nameWithType: ApplicationIntegrationType.GuildInstallable
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.GuildInstallable
  type: Field
  source:
    id: GuildInstallable
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationIntegrationType.cs
    startLine: 35
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Specifies that the integration can be installed on a guild.
  example: []
  syntax:
    content: GuildInstallable = 0
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.UserInstallable
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.UserInstallable
  id: UserInstallable
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
  langs:
  - csharp
  - vb
  name: UserInstallable
  nameWithType: ApplicationIntegrationType.UserInstallable
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.UserInstallable
  type: Field
  source:
    id: UserInstallable
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationIntegrationType.cs
    startLine: 40
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Specifies that the integration can be installed on a user.
  example: []
  syntax:
    content: UserInstallable = 1
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.html
  name: ApplicationIntegrationType
  nameWithType: ApplicationIntegrationType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
