### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings
  commentId: T:Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings
  id: IGuildWidgetSettings
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.ChannelID
  - Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.IsEnabled
  langs:
  - csharp
  - vb
  name: IGuildWidgetSettings
  nameWithType: IGuildWidgetSettings
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings
  type: Interface
  source:
    id: IGuildWidgetSettings
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Guilds\IGuildWidgetSettings.cs
    startLine: 30
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Represents settings related to the status and invite widget for a guild.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public interface IGuildWidgetSettings
    content.vb: >-
      <PublicAPI>

      Public Interface IGuildWidgetSettings
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.IsEnabled
  commentId: P:Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.IsEnabled
  id: IsEnabled
  parent: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings
  langs:
  - csharp
  - vb
  name: IsEnabled
  nameWithType: IGuildWidgetSettings.IsEnabled
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.IsEnabled
  type: Property
  source:
    id: IsEnabled
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Guilds\IGuildWidgetSettings.cs
    startLine: 36
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets a value indicating whether the widget is enabled.
  example: []
  syntax:
    content: bool IsEnabled { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsEnabled As Boolean
  overload: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.IsEnabled*
- uid: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.ChannelID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.ChannelID
  id: ChannelID
  parent: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings
  langs:
  - csharp
  - vb
  name: ChannelID
  nameWithType: IGuildWidgetSettings.ChannelID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.ChannelID
  type: Property
  source:
    id: ChannelID
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Guilds\IGuildWidgetSettings.cs
    startLine: 41
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the ID of the channel invites are generated for.
  example: []
  syntax:
    content: Snowflake? ChannelID { get; }
    parameters: []
    return:
      type: System.Nullable{Remora.Rest.Core.Snowflake}
    content.vb: ReadOnly Property ChannelID As Snowflake?
  overload: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.ChannelID*
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.IsEnabled*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.IsEnabled
  href: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.html#Remora_Discord_API_Abstractions_Objects_IGuildWidgetSettings_IsEnabled
  name: IsEnabled
  nameWithType: IGuildWidgetSettings.IsEnabled
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.IsEnabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.ChannelID*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.ChannelID
  href: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.html#Remora_Discord_API_Abstractions_Objects_IGuildWidgetSettings_ChannelID
  name: ChannelID
  nameWithType: IGuildWidgetSettings.ChannelID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildWidgetSettings.ChannelID
- uid: System.Nullable{Remora.Rest.Core.Snowflake}
  commentId: T:System.Nullable{Remora.Rest.Core.Snowflake}
  parent: System
  definition: System.Nullable`1
  name: Snowflake?
  nameWithType: Snowflake?
  fullName: Remora.Rest.Core.Snowflake?
  spec.csharp:
  - uid: Remora.Rest.Core.Snowflake
    name: Snowflake
    isExternal: true
  - name: '?'
  spec.vb:
  - uid: Remora.Rest.Core.Snowflake
    name: Snowflake
    isExternal: true
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
