### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  id: ApplicationCommandOptionType
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Attachment
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Boolean
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Channel
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Integer
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Mentionable
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Number
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Role
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.String
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.SubCommand
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.SubCommandGroup
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.User
  langs:
  - csharp
  - vb
  name: ApplicationCommandOptionType
  nameWithType: ApplicationCommandOptionType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  type: Enum
  source:
    id: ApplicationCommandOptionType
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 29
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Enumerates various option types.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public enum ApplicationCommandOptionType
    content.vb: >-
      <PublicAPI>

      Public Enum ApplicationCommandOptionType
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.SubCommand
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.SubCommand
  id: SubCommand
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: SubCommand
  nameWithType: ApplicationCommandOptionType.SubCommand
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.SubCommand
  type: Field
  source:
    id: SubCommand
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 35
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is not a value; rather, it is a subcommand.
  example: []
  syntax:
    content: SubCommand = 1
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.SubCommandGroup
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.SubCommandGroup
  id: SubCommandGroup
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: SubCommandGroup
  nameWithType: ApplicationCommandOptionType.SubCommandGroup
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.SubCommandGroup
  type: Field
  source:
    id: SubCommandGroup
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 40
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is not a value; rather, it is a subgroup.
  example: []
  syntax:
    content: SubCommandGroup = 2
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.String
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.String
  id: String
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: String
  nameWithType: ApplicationCommandOptionType.String
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.String
  type: Field
  source:
    id: String
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 45
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is a string.
  example: []
  syntax:
    content: String = 3
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Integer
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Integer
  id: Integer
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: Integer
  nameWithType: ApplicationCommandOptionType.Integer
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Integer
  type: Field
  source:
    id: Integer
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 50
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is an integer.
  example: []
  syntax:
    content: Integer = 4
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Boolean
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Boolean
  id: Boolean
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: Boolean
  nameWithType: ApplicationCommandOptionType.Boolean
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Boolean
  type: Field
  source:
    id: Boolean
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 55
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is a boolean.
  example: []
  syntax:
    content: Boolean = 5
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.User
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.User
  id: User
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: User
  nameWithType: ApplicationCommandOptionType.User
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.User
  type: Field
  source:
    id: User
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 60
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is a user reference.
  example: []
  syntax:
    content: User = 6
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Channel
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Channel
  id: Channel
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: Channel
  nameWithType: ApplicationCommandOptionType.Channel
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Channel
  type: Field
  source:
    id: Channel
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 65
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is a channel reference.
  example: []
  syntax:
    content: Channel = 7
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Role
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Role
  id: Role
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: Role
  nameWithType: ApplicationCommandOptionType.Role
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Role
  type: Field
  source:
    id: Role
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 70
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is a role reference.
  example: []
  syntax:
    content: Role = 8
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Mentionable
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Mentionable
  id: Mentionable
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: Mentionable
  nameWithType: ApplicationCommandOptionType.Mentionable
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Mentionable
  type: Field
  source:
    id: Mentionable
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 75
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is some type of mentionable object (member, role, channel, etc).
  example: []
  syntax:
    content: Mentionable = 9
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Number
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Number
  id: Number
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: Number
  nameWithType: ApplicationCommandOptionType.Number
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Number
  type: Field
  source:
    id: Number
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 80
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is a floating-point number (double precision).
  example: []
  syntax:
    content: Number = 10
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Attachment
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Attachment
  id: Attachment
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  langs:
  - csharp
  - vb
  name: Attachment
  nameWithType: ApplicationCommandOptionType.Attachment
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.Attachment
  type: Field
  source:
    id: Attachment
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandOptionType.cs
    startLine: 85
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The option is an attachment (an image, document, etc).
  example: []
  syntax:
    content: Attachment = 11
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType.html
  name: ApplicationCommandOptionType
  nameWithType: ApplicationCommandOptionType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandOptionType
