### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
  commentId: T:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
  id: IApplicationAuthorizedWebhookEvent
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Guild
  - Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType
  - Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Scopes
  - Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.User
  langs:
  - csharp
  - vb
  name: IApplicationAuthorizedWebhookEvent
  nameWithType: IApplicationAuthorizedWebhookEvent
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
  type: Interface
  source:
    id: IApplicationAuthorizedWebhookEvent
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\WebhookEvents\IApplicationAuthorizedWebhookEvent.cs
    startLine: 31
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Represents a webhook event for when an application is authorized.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public interface IApplicationAuthorizedWebhookEvent
    content.vb: >-
      <PublicAPI>

      Public Interface IApplicationAuthorizedWebhookEvent
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.User
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.User
  id: User
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
  langs:
  - csharp
  - vb
  name: User
  nameWithType: IApplicationAuthorizedWebhookEvent.User
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.User
  type: Property
  source:
    id: User
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\WebhookEvents\IApplicationAuthorizedWebhookEvent.cs
    startLine: 37
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the user that authorized the application.
  example: []
  syntax:
    content: IUser User { get; }
    parameters: []
    return:
      type: Remora.Discord.API.Abstractions.Objects.IUser
    content.vb: ReadOnly Property User As IUser
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.User*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Scopes
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Scopes
  id: Scopes
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
  langs:
  - csharp
  - vb
  name: Scopes
  nameWithType: IApplicationAuthorizedWebhookEvent.Scopes
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Scopes
  type: Property
  source:
    id: Scopes
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\WebhookEvents\IApplicationAuthorizedWebhookEvent.cs
    startLine: 42
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the scopes that the application was authorized for.
  example: []
  syntax:
    content: IReadOnlyList<string> Scopes { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IReadOnlyList{System.String}
    content.vb: ReadOnly Property Scopes As IReadOnlyList(Of String)
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Scopes*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Guild
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Guild
  id: Guild
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
  langs:
  - csharp
  - vb
  name: Guild
  nameWithType: IApplicationAuthorizedWebhookEvent.Guild
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Guild
  type: Property
  source:
    id: Guild
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\WebhookEvents\IApplicationAuthorizedWebhookEvent.cs
    startLine: 47
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the guild that the application was authorized for, if <xref href="Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType" data-throw-if-not-resolved="false"></xref> is <xref href="Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.GuildInstallable" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: Optional<IPartialGuild> Guild { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Optional{Remora.Discord.API.Abstractions.Objects.IPartialGuild}
    content.vb: ReadOnly Property Guild As [Optional](Of IPartialGuild)
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Guild*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType
  id: IntegrationType
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
  langs:
  - csharp
  - vb
  name: IntegrationType
  nameWithType: IApplicationAuthorizedWebhookEvent.IntegrationType
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType
  type: Property
  source:
    id: IntegrationType
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\WebhookEvents\IApplicationAuthorizedWebhookEvent.cs
    startLine: 52
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the integration type of the application.
  example: []
  syntax:
    content: Optional<ApplicationIntegrationType> IntegrationType { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Optional{Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType}
    content.vb: ReadOnly Property IntegrationType As [Optional](Of ApplicationIntegrationType)
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType*
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.User*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.User
  href: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.html#Remora_Discord_API_Abstractions_Objects_IApplicationAuthorizedWebhookEvent_User
  name: User
  nameWithType: IApplicationAuthorizedWebhookEvent.User
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.User
- uid: Remora.Discord.API.Abstractions.Objects.IUser
  commentId: T:Remora.Discord.API.Abstractions.Objects.IUser
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.IUser.html
  name: IUser
  nameWithType: IUser
  fullName: Remora.Discord.API.Abstractions.Objects.IUser
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Scopes*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Scopes
  href: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.html#Remora_Discord_API_Abstractions_Objects_IApplicationAuthorizedWebhookEvent_Scopes
  name: Scopes
  nameWithType: IApplicationAuthorizedWebhookEvent.Scopes
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Scopes
- uid: System.Collections.Generic.IReadOnlyList{System.String}
  commentId: T:System.Collections.Generic.IReadOnlyList{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyList`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<string>
  nameWithType: IReadOnlyList<string>
  fullName: System.Collections.Generic.IReadOnlyList<string>
  nameWithType.vb: IReadOnlyList(Of String)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of String)
  name.vb: IReadOnlyList(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Collections.Generic.IReadOnlyList`1
  commentId: T:System.Collections.Generic.IReadOnlyList`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<T>
  nameWithType: IReadOnlyList<T>
  fullName: System.Collections.Generic.IReadOnlyList<T>
  nameWithType.vb: IReadOnlyList(Of T)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of T)
  name.vb: IReadOnlyList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
  href: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.html#Remora_Discord_API_Abstractions_Objects_IApplicationAuthorizedWebhookEvent_IntegrationType
  name: IntegrationType
  nameWithType: IApplicationAuthorizedWebhookEvent.IntegrationType
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.GuildInstallable
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.GuildInstallable
  href: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.html#Remora_Discord_API_Abstractions_Objects_ApplicationIntegrationType_GuildInstallable
  name: GuildInstallable
  nameWithType: ApplicationIntegrationType.GuildInstallable
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.GuildInstallable
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Guild*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Guild
  href: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.html#Remora_Discord_API_Abstractions_Objects_IApplicationAuthorizedWebhookEvent_Guild
  name: Guild
  nameWithType: IApplicationAuthorizedWebhookEvent.Guild
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.Guild
- uid: Remora.Rest.Core.Optional{Remora.Discord.API.Abstractions.Objects.IPartialGuild}
  commentId: T:Remora.Rest.Core.Optional{Remora.Discord.API.Abstractions.Objects.IPartialGuild}
  parent: Remora.Rest.Core
  definition: Remora.Rest.Core.Optional`1
  href: Remora.Discord.API.Abstractions.Objects.IPartialGuild.html
  name: Optional<IPartialGuild>
  nameWithType: Optional<IPartialGuild>
  fullName: Remora.Rest.Core.Optional<Remora.Discord.API.Abstractions.Objects.IPartialGuild>
  nameWithType.vb: Optional(Of IPartialGuild)
  fullName.vb: Remora.Rest.Core.Optional(Of Remora.Discord.API.Abstractions.Objects.IPartialGuild)
  name.vb: Optional(Of IPartialGuild)
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - uid: Remora.Discord.API.Abstractions.Objects.IPartialGuild
    name: IPartialGuild
    href: Remora.Discord.API.Abstractions.Objects.IPartialGuild.html
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Remora.Discord.API.Abstractions.Objects.IPartialGuild
    name: IPartialGuild
    href: Remora.Discord.API.Abstractions.Objects.IPartialGuild.html
  - name: )
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
  commentId: T:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.html
  name: IApplicationAuthorizedWebhookEvent
  nameWithType: IApplicationAuthorizedWebhookEvent
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent
- uid: Remora.Rest.Core.Optional`1
  commentId: T:Remora.Rest.Core.Optional`1
  isExternal: true
  name: Optional<TValue>
  nameWithType: Optional<TValue>
  fullName: Remora.Rest.Core.Optional<TValue>
  nameWithType.vb: Optional(Of TValue)
  fullName.vb: Remora.Rest.Core.Optional(Of TValue)
  name.vb: Optional(Of TValue)
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TValue
  - name: )
- uid: Remora.Rest.Core
  commentId: N:Remora.Rest.Core
  isExternal: true
  name: Remora.Rest.Core
  nameWithType: Remora.Rest.Core
  fullName: Remora.Rest.Core
  spec.csharp:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
  spec.vb:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType
  href: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.html#Remora_Discord_API_Abstractions_Objects_IApplicationAuthorizedWebhookEvent_IntegrationType
  name: IntegrationType
  nameWithType: IApplicationAuthorizedWebhookEvent.IntegrationType
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationAuthorizedWebhookEvent.IntegrationType
- uid: Remora.Rest.Core.Optional{Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType}
  commentId: T:Remora.Rest.Core.Optional{Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType}
  parent: Remora.Rest.Core
  definition: Remora.Rest.Core.Optional`1
  href: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.html
  name: Optional<ApplicationIntegrationType>
  nameWithType: Optional<ApplicationIntegrationType>
  fullName: Remora.Rest.Core.Optional<Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType>
  nameWithType.vb: Optional(Of ApplicationIntegrationType)
  fullName.vb: Remora.Rest.Core.Optional(Of Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType)
  name.vb: Optional(Of ApplicationIntegrationType)
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - uid: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
    name: ApplicationIntegrationType
    href: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.html
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType
    name: ApplicationIntegrationType
    href: Remora.Discord.API.Abstractions.Objects.ApplicationIntegrationType.html
  - name: )
