### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Gateway.Events.IApplicationCommandPermissionsUpdate
  commentId: T:Remora.Discord.API.Abstractions.Gateway.Events.IApplicationCommandPermissionsUpdate
  id: IApplicationCommandPermissionsUpdate
  parent: Remora.Discord.API.Abstractions.Gateway.Events
  children: []
  langs:
  - csharp
  - vb
  name: IApplicationCommandPermissionsUpdate
  nameWithType: IApplicationCommandPermissionsUpdate
  fullName: Remora.Discord.API.Abstractions.Gateway.Events.IApplicationCommandPermissionsUpdate
  type: Interface
  source:
    id: IApplicationCommandPermissionsUpdate
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Gateway\Events\ApplicationCommands\IApplicationCommandPermissionsUpdate.cs
    startLine: 30
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Gateway.Events
  summary: Represents an update to the permissions of a command.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public interface IApplicationCommandPermissionsUpdate : IGatewayEvent, IGatewayPayloadData, IGuildApplicationCommandPermissions, IPartialGuildApplicationCommandPermissions
    content.vb: >-
      <PublicAPI>

      Public Interface IApplicationCommandPermissionsUpdate Inherits IGatewayEvent, IGatewayPayloadData, IGuildApplicationCommandPermissions, IPartialGuildApplicationCommandPermissions
  inheritedMembers:
  - Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID
  - Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID
  - Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID
  - Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
references:
- uid: Remora.Discord.API.Abstractions.Gateway.Events
  commentId: N:Remora.Discord.API.Abstractions.Gateway.Events
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Gateway.Events
  nameWithType: Remora.Discord.API.Abstractions.Gateway.Events
  fullName: Remora.Discord.API.Abstractions.Gateway.Events
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Gateway
    name: Gateway
    href: Remora.Discord.API.Abstractions.Gateway.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Gateway.Events
    name: Events
    href: Remora.Discord.API.Abstractions.Gateway.Events.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Gateway
    name: Gateway
    href: Remora.Discord.API.Abstractions.Gateway.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Gateway.Events
    name: Events
    href: Remora.Discord.API.Abstractions.Gateway.Events.html
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID
  parent: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  href: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IGuildApplicationCommandPermissions_ID
  name: ID
  nameWithType: IGuildApplicationCommandPermissions.ID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID
  parent: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  href: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IGuildApplicationCommandPermissions_ApplicationID
  name: ApplicationID
  nameWithType: IGuildApplicationCommandPermissions.ApplicationID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID
  parent: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  href: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IGuildApplicationCommandPermissions_GuildID
  name: GuildID
  nameWithType: IGuildApplicationCommandPermissions.GuildID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions
  commentId: P:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions
  parent: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  href: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IGuildApplicationCommandPermissions_Permissions
  name: Permissions
  nameWithType: IGuildApplicationCommandPermissions.Permissions
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  commentId: T:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.html
  name: IGuildApplicationCommandPermissions
  nameWithType: IGuildApplicationCommandPermissions
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
