### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig
  commentId: T:Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig
  id: IApplicationIntegrationTypeConfig
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig.OAuth2InstallParams
  langs:
  - csharp
  - vb
  name: IApplicationIntegrationTypeConfig
  nameWithType: IApplicationIntegrationTypeConfig
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig
  type: Interface
  source:
    id: IApplicationIntegrationTypeConfig
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\IApplicationIntegrationTypeConfig.cs
    startLine: 30
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The integration type configuration for an application.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public interface IApplicationIntegrationTypeConfig
    content.vb: >-
      <PublicAPI>

      Public Interface IApplicationIntegrationTypeConfig
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig.OAuth2InstallParams
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig.OAuth2InstallParams
  id: OAuth2InstallParams
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig
  langs:
  - csharp
  - vb
  name: OAuth2InstallParams
  nameWithType: IApplicationIntegrationTypeConfig.OAuth2InstallParams
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig.OAuth2InstallParams
  type: Property
  source:
    id: OAuth2InstallParams
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\IApplicationIntegrationTypeConfig.cs
    startLine: 36
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the OAuth2 install parameters for the integration type.
  example: []
  syntax:
    content: Optional<IApplicationOAuth2InstallParams> OAuth2InstallParams { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Optional{Remora.Discord.API.Abstractions.Objects.IApplicationOAuth2InstallParams}
    content.vb: ReadOnly Property OAuth2InstallParams As [Optional](Of IApplicationOAuth2InstallParams)
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig.OAuth2InstallParams*
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig.OAuth2InstallParams*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig.OAuth2InstallParams
  href: Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig.html#Remora_Discord_API_Abstractions_Objects_IApplicationIntegrationTypeConfig_OAuth2InstallParams
  name: OAuth2InstallParams
  nameWithType: IApplicationIntegrationTypeConfig.OAuth2InstallParams
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationIntegrationTypeConfig.OAuth2InstallParams
- uid: Remora.Rest.Core.Optional{Remora.Discord.API.Abstractions.Objects.IApplicationOAuth2InstallParams}
  commentId: T:Remora.Rest.Core.Optional{Remora.Discord.API.Abstractions.Objects.IApplicationOAuth2InstallParams}
  parent: Remora.Rest.Core
  definition: Remora.Rest.Core.Optional`1
  href: Remora.Discord.API.Abstractions.Objects.IApplicationOAuth2InstallParams.html
  name: Optional<IApplicationOAuth2InstallParams>
  nameWithType: Optional<IApplicationOAuth2InstallParams>
  fullName: Remora.Rest.Core.Optional<Remora.Discord.API.Abstractions.Objects.IApplicationOAuth2InstallParams>
  nameWithType.vb: Optional(Of IApplicationOAuth2InstallParams)
  fullName.vb: Remora.Rest.Core.Optional(Of Remora.Discord.API.Abstractions.Objects.IApplicationOAuth2InstallParams)
  name.vb: Optional(Of IApplicationOAuth2InstallParams)
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - uid: Remora.Discord.API.Abstractions.Objects.IApplicationOAuth2InstallParams
    name: IApplicationOAuth2InstallParams
    href: Remora.Discord.API.Abstractions.Objects.IApplicationOAuth2InstallParams.html
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Remora.Discord.API.Abstractions.Objects.IApplicationOAuth2InstallParams
    name: IApplicationOAuth2InstallParams
    href: Remora.Discord.API.Abstractions.Objects.IApplicationOAuth2InstallParams.html
  - name: )
- uid: Remora.Rest.Core.Optional`1
  commentId: T:Remora.Rest.Core.Optional`1
  isExternal: true
  name: Optional<TValue>
  nameWithType: Optional<TValue>
  fullName: Remora.Rest.Core.Optional<TValue>
  nameWithType.vb: Optional(Of TValue)
  fullName.vb: Remora.Rest.Core.Optional(Of TValue)
  name.vb: Optional(Of TValue)
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TValue
  - name: )
- uid: Remora.Rest.Core
  commentId: N:Remora.Rest.Core
  isExternal: true
  name: Remora.Rest.Core
  nameWithType: Remora.Rest.Core
  fullName: Remora.Rest.Core
  spec.csharp:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
  spec.vb:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
