### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions
  commentId: T:Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions
  id: IPartialGuildApplicationCommandPermissions
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ApplicationID
  - Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.GuildID
  - Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ID
  - Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.Permissions
  langs:
  - csharp
  - vb
  name: IPartialGuildApplicationCommandPermissions
  nameWithType: IPartialGuildApplicationCommandPermissions
  fullName: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions
  type: Interface
  source:
    id: IPartialGuildApplicationCommandPermissions
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IPartialGuildApplicationCommandPermissions.cs
    startLine: 31
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Represents a set of permissions for a command in a guild.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public interface IPartialGuildApplicationCommandPermissions
    content.vb: >-
      <PublicAPI>

      Public Interface IPartialGuildApplicationCommandPermissions
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ID
  id: ID
  parent: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: ID
  nameWithType: IPartialGuildApplicationCommandPermissions.ID
  fullName: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ID
  type: Property
  source:
    id: ID
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IPartialGuildApplicationCommandPermissions.cs
    startLine: 35
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the ID of the command or the application the permission applies to.
  remarks: >-
    If this ID is that of an application, its permissions apply to all commands that do not have an explicit

    permission set.
  example: []
  syntax:
    content: Optional<Snowflake> ID { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Optional{Remora.Rest.Core.Snowflake}
    content.vb: ReadOnly Property ID As [Optional](Of Snowflake)
  overload: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ID*
- uid: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ApplicationID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ApplicationID
  id: ApplicationID
  parent: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: ApplicationID
  nameWithType: IPartialGuildApplicationCommandPermissions.ApplicationID
  fullName: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ApplicationID
  type: Property
  source:
    id: ApplicationID
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IPartialGuildApplicationCommandPermissions.cs
    startLine: 38
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the ID of the application the command belongs to.
  example: []
  syntax:
    content: Optional<Snowflake> ApplicationID { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Optional{Remora.Rest.Core.Snowflake}
    content.vb: ReadOnly Property ApplicationID As [Optional](Of Snowflake)
  overload: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ApplicationID*
- uid: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.GuildID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.GuildID
  id: GuildID
  parent: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: GuildID
  nameWithType: IPartialGuildApplicationCommandPermissions.GuildID
  fullName: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.GuildID
  type: Property
  source:
    id: GuildID
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IPartialGuildApplicationCommandPermissions.cs
    startLine: 41
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the ID of the guild.
  example: []
  syntax:
    content: Optional<Snowflake> GuildID { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Optional{Remora.Rest.Core.Snowflake}
    content.vb: ReadOnly Property GuildID As [Optional](Of Snowflake)
  overload: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.GuildID*
- uid: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.Permissions
  commentId: P:Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.Permissions
  id: Permissions
  parent: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: Permissions
  nameWithType: IPartialGuildApplicationCommandPermissions.Permissions
  fullName: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.Permissions
  type: Property
  source:
    id: Permissions
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IPartialGuildApplicationCommandPermissions.cs
    startLine: 44
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the permissions for the command in the guild.
  example: []
  syntax:
    content: Optional<IReadOnlyList<IApplicationCommandPermissions>> Permissions { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Optional{System.Collections.Generic.IReadOnlyList{Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions}}
    content.vb: ReadOnly Property Permissions As [Optional](Of IReadOnlyList(Of IApplicationCommandPermissions))
  overload: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.Permissions*
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ID*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ID
  href: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IPartialGuildApplicationCommandPermissions_ID
  name: ID
  nameWithType: IPartialGuildApplicationCommandPermissions.ID
  fullName: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ID
- uid: Remora.Rest.Core.Optional{Remora.Rest.Core.Snowflake}
  commentId: T:Remora.Rest.Core.Optional{Remora.Rest.Core.Snowflake}
  parent: Remora.Rest.Core
  definition: Remora.Rest.Core.Optional`1
  name: Optional<Snowflake>
  nameWithType: Optional<Snowflake>
  fullName: Remora.Rest.Core.Optional<Remora.Rest.Core.Snowflake>
  nameWithType.vb: Optional(Of Snowflake)
  fullName.vb: Remora.Rest.Core.Optional(Of Remora.Rest.Core.Snowflake)
  name.vb: Optional(Of Snowflake)
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - uid: Remora.Rest.Core.Snowflake
    name: Snowflake
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Remora.Rest.Core.Snowflake
    name: Snowflake
    isExternal: true
  - name: )
- uid: Remora.Rest.Core.Optional`1
  commentId: T:Remora.Rest.Core.Optional`1
  isExternal: true
  name: Optional<TValue>
  nameWithType: Optional<TValue>
  fullName: Remora.Rest.Core.Optional<TValue>
  nameWithType.vb: Optional(Of TValue)
  fullName.vb: Remora.Rest.Core.Optional(Of TValue)
  name.vb: Optional(Of TValue)
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TValue
  - name: )
- uid: Remora.Rest.Core
  commentId: N:Remora.Rest.Core
  isExternal: true
  name: Remora.Rest.Core
  nameWithType: Remora.Rest.Core
  fullName: Remora.Rest.Core
  spec.csharp:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
  spec.vb:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
- uid: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ApplicationID*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ApplicationID
  href: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IPartialGuildApplicationCommandPermissions_ApplicationID
  name: ApplicationID
  nameWithType: IPartialGuildApplicationCommandPermissions.ApplicationID
  fullName: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.ApplicationID
- uid: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.GuildID*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.GuildID
  href: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IPartialGuildApplicationCommandPermissions_GuildID
  name: GuildID
  nameWithType: IPartialGuildApplicationCommandPermissions.GuildID
  fullName: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.GuildID
- uid: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.Permissions*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.Permissions
  href: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IPartialGuildApplicationCommandPermissions_Permissions
  name: Permissions
  nameWithType: IPartialGuildApplicationCommandPermissions.Permissions
  fullName: Remora.Discord.API.Abstractions.Objects.IPartialGuildApplicationCommandPermissions.Permissions
- uid: Remora.Rest.Core.Optional{System.Collections.Generic.IReadOnlyList{Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions}}
  commentId: T:Remora.Rest.Core.Optional{System.Collections.Generic.IReadOnlyList{Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions}}
  parent: Remora.Rest.Core
  definition: Remora.Rest.Core.Optional`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: Optional<IReadOnlyList<IApplicationCommandPermissions>>
  nameWithType: Optional<IReadOnlyList<IApplicationCommandPermissions>>
  fullName: Remora.Rest.Core.Optional<System.Collections.Generic.IReadOnlyList<Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions>>
  nameWithType.vb: Optional(Of IReadOnlyList(Of IApplicationCommandPermissions))
  fullName.vb: Remora.Rest.Core.Optional(Of System.Collections.Generic.IReadOnlyList(Of Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions))
  name.vb: Optional(Of IReadOnlyList(Of IApplicationCommandPermissions))
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions
    name: IApplicationCommandPermissions
    href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.html
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions
    name: IApplicationCommandPermissions
    href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.html
  - name: )
  - name: )
