### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions
  commentId: T:Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions
  id: IApplicationCommandPermissions
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.HasPermission
  - Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.ID
  - Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.Type
  langs:
  - csharp
  - vb
  name: IApplicationCommandPermissions
  nameWithType: IApplicationCommandPermissions
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions
  type: Interface
  source:
    id: IApplicationCommandPermissions
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IApplicationCommandPermissions.cs
    startLine: 30
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Represents a single permission for a command.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public interface IApplicationCommandPermissions
    content.vb: >-
      <PublicAPI>

      Public Interface IApplicationCommandPermissions
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.ID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.ID
  id: ID
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: ID
  nameWithType: IApplicationCommandPermissions.ID
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.ID
  type: Property
  source:
    id: ID
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IApplicationCommandPermissions.cs
    startLine: 36
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the ID of the role or user that has been assigned an explicit permission.
  example: []
  syntax:
    content: Snowflake ID { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Snowflake
    content.vb: ReadOnly Property ID As Snowflake
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.ID*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.Type
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.Type
  id: Type
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: IApplicationCommandPermissions.Type
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.Type
  type: Property
  source:
    id: Type
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IApplicationCommandPermissions.cs
    startLine: 41
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the type of the entity that has been assigned an explicit permission.
  example: []
  syntax:
    content: ApplicationCommandPermissionType Type { get; }
    parameters: []
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
    content.vb: ReadOnly Property Type As ApplicationCommandPermissionType
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.Type*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.HasPermission
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.HasPermission
  id: HasPermission
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: HasPermission
  nameWithType: IApplicationCommandPermissions.HasPermission
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.HasPermission
  type: Property
  source:
    id: HasPermission
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IApplicationCommandPermissions.cs
    startLine: 46
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets a value indicating whether the referenced entity has permission to use the command.
  example: []
  syntax:
    content: bool HasPermission { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property HasPermission As Boolean
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.HasPermission*
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.ID*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.ID
  href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IApplicationCommandPermissions_ID
  name: ID
  nameWithType: IApplicationCommandPermissions.ID
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.ID
- uid: Remora.Rest.Core.Snowflake
  commentId: T:Remora.Rest.Core.Snowflake
  parent: Remora.Rest.Core
  isExternal: true
  name: Snowflake
  nameWithType: Snowflake
  fullName: Remora.Rest.Core.Snowflake
- uid: Remora.Rest.Core
  commentId: N:Remora.Rest.Core
  isExternal: true
  name: Remora.Rest.Core
  nameWithType: Remora.Rest.Core
  fullName: Remora.Rest.Core
  spec.csharp:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
  spec.vb:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.Type*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.Type
  href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IApplicationCommandPermissions_Type
  name: Type
  nameWithType: IApplicationCommandPermissions.Type
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.Type
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.html
  name: ApplicationCommandPermissionType
  nameWithType: ApplicationCommandPermissionType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.HasPermission*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.HasPermission
  href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IApplicationCommandPermissions_HasPermission
  name: HasPermission
  nameWithType: IApplicationCommandPermissions.HasPermission
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.HasPermission
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
