### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  id: ApplicationFlags
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.ApplicationFlags.ApplicationAutoModerationRuleCreateBadge
  - Remora.Discord.API.Abstractions.Objects.ApplicationFlags.ApplicationCommandBadge
  - Remora.Discord.API.Abstractions.Objects.ApplicationFlags.Embedded
  - Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayGuildMembers
  - Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayGuildMembersLimited
  - Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayMessageContent
  - Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayMessageContentLimited
  - Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayPresence
  - Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayPresenceLimited
  - Remora.Discord.API.Abstractions.Objects.ApplicationFlags.VerificationPendingGuildLimit
  langs:
  - csharp
  - vb
  name: ApplicationFlags
  nameWithType: ApplicationFlags
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  type: Enum
  source:
    id: ApplicationFlags
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 30
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Enumerates various application flags.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      [Flags]

      public enum ApplicationFlags
    content.vb: >-
      <PublicAPI>

      <Flags>

      Public Enum ApplicationFlags
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
  - type: System.FlagsAttribute
    ctor: System.FlagsAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.ApplicationAutoModerationRuleCreateBadge
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationFlags.ApplicationAutoModerationRuleCreateBadge
  id: ApplicationAutoModerationRuleCreateBadge
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  langs:
  - csharp
  - vb
  name: ApplicationAutoModerationRuleCreateBadge
  nameWithType: ApplicationFlags.ApplicationAutoModerationRuleCreateBadge
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.ApplicationAutoModerationRuleCreateBadge
  type: Field
  source:
    id: ApplicationAutoModerationRuleCreateBadge
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 36
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The application uses the auto moderation API.
  example: []
  syntax:
    content: ApplicationAutoModerationRuleCreateBadge = 64
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayPresence
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayPresence
  id: GatewayPresence
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  langs:
  - csharp
  - vb
  name: GatewayPresence
  nameWithType: ApplicationFlags.GatewayPresence
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayPresence
  type: Field
  source:
    id: GatewayPresence
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 41
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The application is allowed to receive presence information over the gateway.
  example: []
  syntax:
    content: GatewayPresence = 4096
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayPresenceLimited
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayPresenceLimited
  id: GatewayPresenceLimited
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  langs:
  - csharp
  - vb
  name: GatewayPresenceLimited
  nameWithType: ApplicationFlags.GatewayPresenceLimited
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayPresenceLimited
  type: Field
  source:
    id: GatewayPresenceLimited
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 46
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The application is allowed to receive limited presence information over the gateway.
  example: []
  syntax:
    content: GatewayPresenceLimited = 8192
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayGuildMembers
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayGuildMembers
  id: GatewayGuildMembers
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  langs:
  - csharp
  - vb
  name: GatewayGuildMembers
  nameWithType: ApplicationFlags.GatewayGuildMembers
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayGuildMembers
  type: Field
  source:
    id: GatewayGuildMembers
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 51
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The application is allowed to receive guild members over the gateway.
  example: []
  syntax:
    content: GatewayGuildMembers = 16384
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayGuildMembersLimited
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayGuildMembersLimited
  id: GatewayGuildMembersLimited
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  langs:
  - csharp
  - vb
  name: GatewayGuildMembersLimited
  nameWithType: ApplicationFlags.GatewayGuildMembersLimited
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayGuildMembersLimited
  type: Field
  source:
    id: GatewayGuildMembersLimited
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 56
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The application is allowed to receive limited guild members over the gateway.
  example: []
  syntax:
    content: GatewayGuildMembersLimited = 32768
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.VerificationPendingGuildLimit
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationFlags.VerificationPendingGuildLimit
  id: VerificationPendingGuildLimit
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  langs:
  - csharp
  - vb
  name: VerificationPendingGuildLimit
  nameWithType: ApplicationFlags.VerificationPendingGuildLimit
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.VerificationPendingGuildLimit
  type: Field
  source:
    id: VerificationPendingGuildLimit
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 61
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The application is currently pending verification and has hit the guild limit.
  example: []
  syntax:
    content: VerificationPendingGuildLimit = 65536
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.Embedded
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationFlags.Embedded
  id: Embedded
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  langs:
  - csharp
  - vb
  name: Embedded
  nameWithType: ApplicationFlags.Embedded
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.Embedded
  type: Field
  source:
    id: Embedded
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 66
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The application is embedded.
  example: []
  syntax:
    content: Embedded = 131072
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayMessageContent
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayMessageContent
  id: GatewayMessageContent
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  langs:
  - csharp
  - vb
  name: GatewayMessageContent
  nameWithType: ApplicationFlags.GatewayMessageContent
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayMessageContent
  type: Field
  source:
    id: GatewayMessageContent
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 71
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The application has access to message contents over the gateway.
  example: []
  syntax:
    content: GatewayMessageContent = 262144
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayMessageContentLimited
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayMessageContentLimited
  id: GatewayMessageContentLimited
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  langs:
  - csharp
  - vb
  name: GatewayMessageContentLimited
  nameWithType: ApplicationFlags.GatewayMessageContentLimited
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.GatewayMessageContentLimited
  type: Field
  source:
    id: GatewayMessageContentLimited
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 76
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The application's access to message contents over the gateway is limited.
  example: []
  syntax:
    content: GatewayMessageContentLimited = 524288
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.ApplicationCommandBadge
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationFlags.ApplicationCommandBadge
  id: ApplicationCommandBadge
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  langs:
  - csharp
  - vb
  name: ApplicationCommandBadge
  nameWithType: ApplicationFlags.ApplicationCommandBadge
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.ApplicationCommandBadge
  type: Field
  source:
    id: ApplicationCommandBadge
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationFlags.cs
    startLine: 81
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The application has registered global commands.
  example: []
  syntax:
    content: ApplicationCommandBadge = 8388608
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationFlags
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.ApplicationFlags.html
  name: ApplicationFlags
  nameWithType: ApplicationFlags
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationFlags
