### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
  id: ApplicationCommandType
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.ChatInput
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.Message
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.User
  langs:
  - csharp
  - vb
  name: ApplicationCommandType
  nameWithType: ApplicationCommandType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
  type: Enum
  source:
    id: ApplicationCommandType
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandType.cs
    startLine: 29
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Enumerates various application command types.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public enum ApplicationCommandType
    content.vb: >-
      <PublicAPI>

      Public Enum ApplicationCommandType
  extensionMethods:
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.ChatInput
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.ChatInput
  id: ChatInput
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
  langs:
  - csharp
  - vb
  name: ChatInput
  nameWithType: ApplicationCommandType.ChatInput
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.ChatInput
  type: Field
  source:
    id: ChatInput
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandType.cs
    startLine: 35
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Slash commands; a text-based command that shows up when a user types /.
  example: []
  syntax:
    content: ChatInput = 1
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.User
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.User
  id: User
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
  langs:
  - csharp
  - vb
  name: User
  nameWithType: ApplicationCommandType.User
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.User
  type: Field
  source:
    id: User
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandType.cs
    startLine: 40
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: A UI-based command that shows up when you right click or tap on a user.
  example: []
  syntax:
    content: User = 2
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.Message
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.Message
  id: Message
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: ApplicationCommandType.Message
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.Message
  type: Field
  source:
    id: Message
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandType.cs
    startLine: 45
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: A UI-based command that shows up when you right click or tap on a messages.
  example: []
  syntax:
    content: Message = 3
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName
  commentId: M:Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName(Remora.Discord.API.Abstractions.Objects.ApplicationCommandType)
  parent: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions
  definition: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName(Remora.Discord.API.Abstractions.Objects.ApplicationCommandType)
  href: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.html#Remora_Discord_Commands_Extensions_ApplicationCommandTypeExtensions_AsParameterName_Remora_Discord_API_Abstractions_Objects_ApplicationCommandType_
  name: AsParameterName(ApplicationCommandType)
  nameWithType: ApplicationCommandTypeExtensions.AsParameterName(ApplicationCommandType)
  fullName: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName(Remora.Discord.API.Abstractions.Objects.ApplicationCommandType)
  spec.csharp:
  - uid: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName(Remora.Discord.API.Abstractions.Objects.ApplicationCommandType)
    name: AsParameterName
    href: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.html#Remora_Discord_Commands_Extensions_ApplicationCommandTypeExtensions_AsParameterName_Remora_Discord_API_Abstractions_Objects_ApplicationCommandType_
  - name: (
  - uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
    name: ApplicationCommandType
    href: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.html
  - name: )
  spec.vb:
  - uid: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName(Remora.Discord.API.Abstractions.Objects.ApplicationCommandType)
    name: AsParameterName
    href: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.html#Remora_Discord_Commands_Extensions_ApplicationCommandTypeExtensions_AsParameterName_Remora_Discord_API_Abstractions_Objects_ApplicationCommandType_
  - name: (
  - uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
    name: ApplicationCommandType
    href: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.html
  - name: )
- uid: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName(Remora.Discord.API.Abstractions.Objects.ApplicationCommandType)
  commentId: M:Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName(Remora.Discord.API.Abstractions.Objects.ApplicationCommandType)
  href: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.html#Remora_Discord_Commands_Extensions_ApplicationCommandTypeExtensions_AsParameterName_Remora_Discord_API_Abstractions_Objects_ApplicationCommandType_
  name: AsParameterName(ApplicationCommandType)
  nameWithType: ApplicationCommandTypeExtensions.AsParameterName(ApplicationCommandType)
  fullName: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName(Remora.Discord.API.Abstractions.Objects.ApplicationCommandType)
  spec.csharp:
  - uid: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName(Remora.Discord.API.Abstractions.Objects.ApplicationCommandType)
    name: AsParameterName
    href: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.html#Remora_Discord_Commands_Extensions_ApplicationCommandTypeExtensions_AsParameterName_Remora_Discord_API_Abstractions_Objects_ApplicationCommandType_
  - name: (
  - uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
    name: ApplicationCommandType
    href: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.html
  - name: )
  spec.vb:
  - uid: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.AsParameterName(Remora.Discord.API.Abstractions.Objects.ApplicationCommandType)
    name: AsParameterName
    href: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.html#Remora_Discord_Commands_Extensions_ApplicationCommandTypeExtensions_AsParameterName_Remora_Discord_API_Abstractions_Objects_ApplicationCommandType_
  - name: (
  - uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
    name: ApplicationCommandType
    href: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.html
  - name: )
- uid: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions
  commentId: T:Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions
  parent: Remora.Discord.Commands.Extensions
  href: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions.html
  name: ApplicationCommandTypeExtensions
  nameWithType: ApplicationCommandTypeExtensions
  fullName: Remora.Discord.Commands.Extensions.ApplicationCommandTypeExtensions
- uid: Remora.Discord.Commands.Extensions
  commentId: N:Remora.Discord.Commands.Extensions
  href: Remora.html
  name: Remora.Discord.Commands.Extensions
  nameWithType: Remora.Discord.Commands.Extensions
  fullName: Remora.Discord.Commands.Extensions
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.Commands
    name: Commands
    href: Remora.Discord.Commands.html
  - name: .
  - uid: Remora.Discord.Commands.Extensions
    name: Extensions
    href: Remora.Discord.Commands.Extensions.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.Commands
    name: Commands
    href: Remora.Discord.Commands.html
  - name: .
  - uid: Remora.Discord.Commands.Extensions
    name: Extensions
    href: Remora.Discord.Commands.Extensions.html
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType.html
  name: ApplicationCommandType
  nameWithType: ApplicationCommandType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandType
