### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  commentId: T:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  id: IGuildApplicationCommandPermissions
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID
  - Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID
  - Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID
  - Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions
  langs:
  - csharp
  - vb
  name: IGuildApplicationCommandPermissions
  nameWithType: IGuildApplicationCommandPermissions
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  type: Interface
  source:
    id: IGuildApplicationCommandPermissions
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IGuildApplicationCommandPermissions.cs
    startLine: 31
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Represents a set of permissions for a command in a guild.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public interface IGuildApplicationCommandPermissions : IPartialGuildApplicationCommandPermissions
    content.vb: >-
      <PublicAPI>

      Public Interface IGuildApplicationCommandPermissions Inherits IPartialGuildApplicationCommandPermissions
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID
  id: ID
  parent: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: ID
  nameWithType: IGuildApplicationCommandPermissions.ID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID
  type: Property
  source:
    id: ID
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IGuildApplicationCommandPermissions.cs
    startLine: 41
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the ID of the command or the application the permission applies to.
  remarks: >-
    If this ID is that of an application, its permissions apply to all commands that do not have an explicit

    permission set.
  example: []
  syntax:
    content: Snowflake ID { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Snowflake
    content.vb: ReadOnly Property ID As Snowflake
  overload: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID*
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID
  id: ApplicationID
  parent: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: ApplicationID
  nameWithType: IGuildApplicationCommandPermissions.ApplicationID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID
  type: Property
  source:
    id: ApplicationID
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IGuildApplicationCommandPermissions.cs
    startLine: 46
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the ID of the application the command belongs to.
  example: []
  syntax:
    content: Snowflake ApplicationID { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Snowflake
    content.vb: ReadOnly Property ApplicationID As Snowflake
  overload: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID*
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID
  commentId: P:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID
  id: GuildID
  parent: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: GuildID
  nameWithType: IGuildApplicationCommandPermissions.GuildID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID
  type: Property
  source:
    id: GuildID
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IGuildApplicationCommandPermissions.cs
    startLine: 51
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the ID of the guild.
  example: []
  syntax:
    content: Snowflake GuildID { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Snowflake
    content.vb: ReadOnly Property GuildID As Snowflake
  overload: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID*
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions
  commentId: P:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions
  id: Permissions
  parent: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions
  langs:
  - csharp
  - vb
  name: Permissions
  nameWithType: IGuildApplicationCommandPermissions.Permissions
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions
  type: Property
  source:
    id: Permissions
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IGuildApplicationCommandPermissions.cs
    startLine: 56
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the permissions for the command in the guild.
  example: []
  syntax:
    content: IReadOnlyList<IApplicationCommandPermissions> Permissions { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IReadOnlyList{Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions}
    content.vb: ReadOnly Property Permissions As IReadOnlyList(Of IApplicationCommandPermissions)
  overload: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions*
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID
  href: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IGuildApplicationCommandPermissions_ID
  name: ID
  nameWithType: IGuildApplicationCommandPermissions.ID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ID
- uid: Remora.Rest.Core.Snowflake
  commentId: T:Remora.Rest.Core.Snowflake
  parent: Remora.Rest.Core
  isExternal: true
  name: Snowflake
  nameWithType: Snowflake
  fullName: Remora.Rest.Core.Snowflake
- uid: Remora.Rest.Core
  commentId: N:Remora.Rest.Core
  isExternal: true
  name: Remora.Rest.Core
  nameWithType: Remora.Rest.Core
  fullName: Remora.Rest.Core
  spec.csharp:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
  spec.vb:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID
  href: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IGuildApplicationCommandPermissions_ApplicationID
  name: ApplicationID
  nameWithType: IGuildApplicationCommandPermissions.ApplicationID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.ApplicationID
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID
  href: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IGuildApplicationCommandPermissions_GuildID
  name: GuildID
  nameWithType: IGuildApplicationCommandPermissions.GuildID
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.GuildID
- uid: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions
  href: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.html#Remora_Discord_API_Abstractions_Objects_IGuildApplicationCommandPermissions_Permissions
  name: Permissions
  nameWithType: IGuildApplicationCommandPermissions.Permissions
  fullName: Remora.Discord.API.Abstractions.Objects.IGuildApplicationCommandPermissions.Permissions
- uid: System.Collections.Generic.IReadOnlyList{Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions}
  commentId: T:System.Collections.Generic.IReadOnlyList{Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyList`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<IApplicationCommandPermissions>
  nameWithType: IReadOnlyList<IApplicationCommandPermissions>
  fullName: System.Collections.Generic.IReadOnlyList<Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions>
  nameWithType.vb: IReadOnlyList(Of IApplicationCommandPermissions)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions)
  name.vb: IReadOnlyList(Of IApplicationCommandPermissions)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions
    name: IApplicationCommandPermissions
    href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions
    name: IApplicationCommandPermissions
    href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandPermissions.html
  - name: )
- uid: System.Collections.Generic.IReadOnlyList`1
  commentId: T:System.Collections.Generic.IReadOnlyList`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<T>
  nameWithType: IReadOnlyList<T>
  fullName: System.Collections.Generic.IReadOnlyList<T>
  nameWithType.vb: IReadOnlyList(Of T)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of T)
  name.vb: IReadOnlyList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
