### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
  id: ApplicationCommandPermissionType
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.Channel
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.Role
  - Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.User
  langs:
  - csharp
  - vb
  name: ApplicationCommandPermissionType
  nameWithType: ApplicationCommandPermissionType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
  type: Enum
  source:
    id: ApplicationCommandPermissionType
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandPermissionType.cs
    startLine: 29
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Enumerates application permission types.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public enum ApplicationCommandPermissionType
    content.vb: >-
      <PublicAPI>

      Public Enum ApplicationCommandPermissionType
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.Role
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.Role
  id: Role
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
  langs:
  - csharp
  - vb
  name: Role
  nameWithType: ApplicationCommandPermissionType.Role
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.Role
  type: Field
  source:
    id: Role
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandPermissionType.cs
    startLine: 35
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The permission applies to a role.
  example: []
  syntax:
    content: Role = 1
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.User
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.User
  id: User
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
  langs:
  - csharp
  - vb
  name: User
  nameWithType: ApplicationCommandPermissionType.User
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.User
  type: Field
  source:
    id: User
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandPermissionType.cs
    startLine: 40
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The permission applies to a user.
  example: []
  syntax:
    content: User = 2
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.Channel
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.Channel
  id: Channel
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
  langs:
  - csharp
  - vb
  name: Channel
  nameWithType: ApplicationCommandPermissionType.Channel
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.Channel
  type: Field
  source:
    id: Channel
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\ApplicationCommandPermissionType.cs
    startLine: 45
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The permission applies to a channel.
  example: []
  syntax:
    content: Channel = 3
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType.html
  name: ApplicationCommandPermissionType
  nameWithType: ApplicationCommandPermissionType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationCommandPermissionType
