### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice
  commentId: T:Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice
  id: IApplicationCommandOptionChoice
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Name
  - Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalizations
  - Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalized
  - Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Value
  langs:
  - csharp
  - vb
  name: IApplicationCommandOptionChoice
  nameWithType: IApplicationCommandOptionChoice
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice
  type: Interface
  source:
    id: IApplicationCommandOptionChoice
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IApplicationCommandOptionChoice.cs
    startLine: 32
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Represents a choice available to a user.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public interface IApplicationCommandOptionChoice
    content.vb: >-
      <PublicAPI>

      Public Interface IApplicationCommandOptionChoice
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Name
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Name
  id: Name
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: IApplicationCommandOptionChoice.Name
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Name
  type: Property
  source:
    id: Name
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IApplicationCommandOptionChoice.cs
    startLine: 39
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the name of the choice.
  remarks: This can be up to 100 characters.
  example: []
  syntax:
    content: string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Name As String
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Name*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Value
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Value
  id: Value
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: IApplicationCommandOptionChoice.Value
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Value
  type: Property
  source:
    id: Value
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IApplicationCommandOptionChoice.cs
    startLine: 44
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the value of the choice.
  example: []
  syntax:
    content: OneOf<string, int, double> Value { get; }
    parameters: []
    return:
      type: OneOf.OneOf{System.String,System.Int32,System.Double}
    content.vb: ReadOnly Property Value As OneOf(Of String, Integer, Double)
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Value*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalizations
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalizations
  id: NameLocalizations
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice
  langs:
  - csharp
  - vb
  name: NameLocalizations
  nameWithType: IApplicationCommandOptionChoice.NameLocalizations
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalizations
  type: Property
  source:
    id: NameLocalizations
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IApplicationCommandOptionChoice.cs
    startLine: 49
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the localized names of the option.
  example: []
  syntax:
    content: Optional<IReadOnlyDictionary<string, string>?> NameLocalizations { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Optional{System.Collections.Generic.IReadOnlyDictionary{System.String,System.String}}
    content.vb: ReadOnly Property NameLocalizations As [Optional](Of IReadOnlyDictionary(Of String, String))
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalizations*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalized
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalized
  id: NameLocalized
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice
  langs:
  - csharp
  - vb
  name: NameLocalized
  nameWithType: IApplicationCommandOptionChoice.NameLocalized
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalized
  type: Property
  source:
    id: NameLocalized
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Interactions\ApplicationCommands\IApplicationCommandOptionChoice.cs
    startLine: 57
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the localized name of the option.
  remarks: This field is only supplied by Discord as a response, and is not used to set the actual localized string.
  example: []
  syntax:
    content: Optional<string> NameLocalized { get; }
    parameters: []
    return:
      type: Remora.Rest.Core.Optional{System.String}
    content.vb: ReadOnly Property NameLocalized As [Optional](Of String)
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalized*
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Name*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Name
  href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.html#Remora_Discord_API_Abstractions_Objects_IApplicationCommandOptionChoice_Name
  name: Name
  nameWithType: IApplicationCommandOptionChoice.Name
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Value*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Value
  href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.html#Remora_Discord_API_Abstractions_Objects_IApplicationCommandOptionChoice_Value
  name: Value
  nameWithType: IApplicationCommandOptionChoice.Value
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.Value
- uid: OneOf.OneOf{System.String,System.Int32,System.Double}
  commentId: T:OneOf.OneOf{System.String,System.Int32,System.Double}
  parent: OneOf
  definition: OneOf.OneOf`3
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: OneOf<string, int, double>
  nameWithType: OneOf<string, int, double>
  fullName: OneOf.OneOf<string, int, double>
  nameWithType.vb: OneOf(Of String, Integer, Double)
  fullName.vb: OneOf.OneOf(Of String, Integer, Double)
  name.vb: OneOf(Of String, Integer, Double)
  spec.csharp:
  - uid: OneOf.OneOf`3
    name: OneOf
    isExternal: true
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ','
  - name: " "
  - uid: System.Double
    name: double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: '>'
  spec.vb:
  - uid: OneOf.OneOf`3
    name: OneOf
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ','
  - name: " "
  - uid: System.Double
    name: Double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: )
- uid: OneOf.OneOf`3
  commentId: T:OneOf.OneOf`3
  isExternal: true
  name: OneOf<T0, T1, T2>
  nameWithType: OneOf<T0, T1, T2>
  fullName: OneOf.OneOf<T0, T1, T2>
  nameWithType.vb: OneOf(Of T0, T1, T2)
  fullName.vb: OneOf.OneOf(Of T0, T1, T2)
  name.vb: OneOf(Of T0, T1, T2)
  spec.csharp:
  - uid: OneOf.OneOf`3
    name: OneOf
    isExternal: true
  - name: <
  - name: T0
  - name: ','
  - name: " "
  - name: T1
  - name: ','
  - name: " "
  - name: T2
  - name: '>'
  spec.vb:
  - uid: OneOf.OneOf`3
    name: OneOf
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T0
  - name: ','
  - name: " "
  - name: T1
  - name: ','
  - name: " "
  - name: T2
  - name: )
- uid: OneOf
  commentId: N:OneOf
  isExternal: true
  name: OneOf
  nameWithType: OneOf
  fullName: OneOf
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalizations*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalizations
  href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.html#Remora_Discord_API_Abstractions_Objects_IApplicationCommandOptionChoice_NameLocalizations
  name: NameLocalizations
  nameWithType: IApplicationCommandOptionChoice.NameLocalizations
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalizations
- uid: Remora.Rest.Core.Optional{System.Collections.Generic.IReadOnlyDictionary{System.String,System.String}}
  commentId: T:Remora.Rest.Core.Optional{System.Collections.Generic.IReadOnlyDictionary{System.String,System.String}}
  parent: Remora.Rest.Core
  definition: Remora.Rest.Core.Optional`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  name: Optional<IReadOnlyDictionary<string, string>>
  nameWithType: Optional<IReadOnlyDictionary<string, string>>
  fullName: Remora.Rest.Core.Optional<System.Collections.Generic.IReadOnlyDictionary<string, string>>
  nameWithType.vb: Optional(Of IReadOnlyDictionary(Of String, String))
  fullName.vb: Remora.Rest.Core.Optional(Of System.Collections.Generic.IReadOnlyDictionary(Of String, String))
  name.vb: Optional(Of IReadOnlyDictionary(Of String, String))
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - uid: System.Collections.Generic.IReadOnlyDictionary`2
    name: IReadOnlyDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Collections.Generic.IReadOnlyDictionary`2
    name: IReadOnlyDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  - name: )
- uid: Remora.Rest.Core.Optional`1
  commentId: T:Remora.Rest.Core.Optional`1
  isExternal: true
  name: Optional<TValue>
  nameWithType: Optional<TValue>
  fullName: Remora.Rest.Core.Optional<TValue>
  nameWithType.vb: Optional(Of TValue)
  fullName.vb: Remora.Rest.Core.Optional(Of TValue)
  name.vb: Optional(Of TValue)
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TValue
  - name: )
- uid: Remora.Rest.Core
  commentId: N:Remora.Rest.Core
  isExternal: true
  name: Remora.Rest.Core
  nameWithType: Remora.Rest.Core
  fullName: Remora.Rest.Core
  spec.csharp:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
  spec.vb:
  - uid: Remora
    name: Remora
    isExternal: true
  - name: .
  - uid: Remora.Rest
    name: Rest
    isExternal: true
  - name: .
  - uid: Remora.Rest.Core
    name: Core
    isExternal: true
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalized*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalized
  href: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.html#Remora_Discord_API_Abstractions_Objects_IApplicationCommandOptionChoice_NameLocalized
  name: NameLocalized
  nameWithType: IApplicationCommandOptionChoice.NameLocalized
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationCommandOptionChoice.NameLocalized
- uid: Remora.Rest.Core.Optional{System.String}
  commentId: T:Remora.Rest.Core.Optional{System.String}
  parent: Remora.Rest.Core
  definition: Remora.Rest.Core.Optional`1
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: Optional<string>
  nameWithType: Optional<string>
  fullName: Remora.Rest.Core.Optional<string>
  nameWithType.vb: Optional(Of String)
  fullName.vb: Remora.Rest.Core.Optional(Of String)
  name.vb: Optional(Of String)
  spec.csharp:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: Remora.Rest.Core.Optional`1
    name: Optional
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
