### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  id: ApplicationRoleConnectionMetadataType
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.BooleanEqual
  - Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.BooleanNotEqual
  - Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.DateTimeGreaterThanOrEqual
  - Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.DateTimeLessThanOrEqual
  - Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerEqual
  - Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerGreaterThanOrEqual
  - Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerLessThanOrEqual
  - Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerNotEqual
  langs:
  - csharp
  - vb
  name: ApplicationRoleConnectionMetadataType
  nameWithType: ApplicationRoleConnectionMetadataType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  type: Enum
  source:
    id: ApplicationRoleConnectionMetadataType
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationRoleConnectionMetadataType.cs
    startLine: 29
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Enumerates various application role connection metadata types.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public enum ApplicationRoleConnectionMetadataType
    content.vb: >-
      <PublicAPI>

      Public Enum ApplicationRoleConnectionMetadataType
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerLessThanOrEqual
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerLessThanOrEqual
  id: IntegerLessThanOrEqual
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  langs:
  - csharp
  - vb
  name: IntegerLessThanOrEqual
  nameWithType: ApplicationRoleConnectionMetadataType.IntegerLessThanOrEqual
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerLessThanOrEqual
  type: Field
  source:
    id: IntegerLessThanOrEqual
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationRoleConnectionMetadataType.cs
    startLine: 35
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The metadata value (integer) is less than or equal to the guild's configured value (integer).
  example: []
  syntax:
    content: IntegerLessThanOrEqual = 1
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerGreaterThanOrEqual
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerGreaterThanOrEqual
  id: IntegerGreaterThanOrEqual
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  langs:
  - csharp
  - vb
  name: IntegerGreaterThanOrEqual
  nameWithType: ApplicationRoleConnectionMetadataType.IntegerGreaterThanOrEqual
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerGreaterThanOrEqual
  type: Field
  source:
    id: IntegerGreaterThanOrEqual
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationRoleConnectionMetadataType.cs
    startLine: 40
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The metadata value (integer) is greater than or equal to the guild's configured value (integer).
  example: []
  syntax:
    content: IntegerGreaterThanOrEqual = 2
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerEqual
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerEqual
  id: IntegerEqual
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  langs:
  - csharp
  - vb
  name: IntegerEqual
  nameWithType: ApplicationRoleConnectionMetadataType.IntegerEqual
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerEqual
  type: Field
  source:
    id: IntegerEqual
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationRoleConnectionMetadataType.cs
    startLine: 45
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The metadata value (integer) is equal to the guild's configured value (integer).
  example: []
  syntax:
    content: IntegerEqual = 3
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerNotEqual
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerNotEqual
  id: IntegerNotEqual
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  langs:
  - csharp
  - vb
  name: IntegerNotEqual
  nameWithType: ApplicationRoleConnectionMetadataType.IntegerNotEqual
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.IntegerNotEqual
  type: Field
  source:
    id: IntegerNotEqual
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationRoleConnectionMetadataType.cs
    startLine: 50
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The metadata value (integer) is not equal to the guild's configured value (integer).
  example: []
  syntax:
    content: IntegerNotEqual = 4
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.DateTimeLessThanOrEqual
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.DateTimeLessThanOrEqual
  id: DateTimeLessThanOrEqual
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  langs:
  - csharp
  - vb
  name: DateTimeLessThanOrEqual
  nameWithType: ApplicationRoleConnectionMetadataType.DateTimeLessThanOrEqual
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.DateTimeLessThanOrEqual
  type: Field
  source:
    id: DateTimeLessThanOrEqual
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationRoleConnectionMetadataType.cs
    startLine: 56
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: >-
    The metadata value (ISO8601 string) is less than or equal to the guild's configured value (integer; days before

    current date).
  example: []
  syntax:
    content: DateTimeLessThanOrEqual = 5
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.DateTimeGreaterThanOrEqual
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.DateTimeGreaterThanOrEqual
  id: DateTimeGreaterThanOrEqual
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  langs:
  - csharp
  - vb
  name: DateTimeGreaterThanOrEqual
  nameWithType: ApplicationRoleConnectionMetadataType.DateTimeGreaterThanOrEqual
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.DateTimeGreaterThanOrEqual
  type: Field
  source:
    id: DateTimeGreaterThanOrEqual
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationRoleConnectionMetadataType.cs
    startLine: 62
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: >-
    The metadata value (ISO8601 string) is greater than or equal to the guild's configured value (integer; days

    before current date).
  example: []
  syntax:
    content: DateTimeGreaterThanOrEqual = 6
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.BooleanEqual
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.BooleanEqual
  id: BooleanEqual
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  langs:
  - csharp
  - vb
  name: BooleanEqual
  nameWithType: ApplicationRoleConnectionMetadataType.BooleanEqual
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.BooleanEqual
  type: Field
  source:
    id: BooleanEqual
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationRoleConnectionMetadataType.cs
    startLine: 67
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The metadata value (integer) is equal to the guild's configured value (integer; 1).
  example: []
  syntax:
    content: BooleanEqual = 7
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.BooleanNotEqual
  commentId: F:Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.BooleanNotEqual
  id: BooleanNotEqual
  parent: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  langs:
  - csharp
  - vb
  name: BooleanNotEqual
  nameWithType: ApplicationRoleConnectionMetadataType.BooleanNotEqual
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.BooleanNotEqual
  type: Field
  source:
    id: BooleanNotEqual
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\ApplicationRoleConnectionMetadataType.cs
    startLine: 72
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: The metadata value (integer) is not equal to the guild's configured value (integer; 1).
  example: []
  syntax:
    content: BooleanNotEqual = 8
    return:
      type: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  commentId: T:Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType.html
  name: ApplicationRoleConnectionMetadataType
  nameWithType: ApplicationRoleConnectionMetadataType
  fullName: Remora.Discord.API.Abstractions.Objects.ApplicationRoleConnectionMetadataType
