### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection
  commentId: T:Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection
  id: IApplicationRoleConnection
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.Metadata
  - Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformName
  - Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformUsername
  langs:
  - csharp
  - vb
  name: IApplicationRoleConnection
  nameWithType: IApplicationRoleConnection
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection
  type: Interface
  source:
    id: IApplicationRoleConnection
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Users\IApplicationRoleConnection.cs
    startLine: 30
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Represents a role connection that an application has attached to an user.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public interface IApplicationRoleConnection
    content.vb: >-
      <PublicAPI>

      Public Interface IApplicationRoleConnection
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformName
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformName
  id: PlatformName
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection
  langs:
  - csharp
  - vb
  name: PlatformName
  nameWithType: IApplicationRoleConnection.PlatformName
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformName
  type: Property
  source:
    id: PlatformName
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Users\IApplicationRoleConnection.cs
    startLine: 37
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the vanity name of the platform a bot has connected.
  remarks: The length of the platform username must be max. 50 characters.
  example: []
  syntax:
    content: string? PlatformName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property PlatformName As String
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformName*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformUsername
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformUsername
  id: PlatformUsername
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection
  langs:
  - csharp
  - vb
  name: PlatformUsername
  nameWithType: IApplicationRoleConnection.PlatformUsername
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformUsername
  type: Property
  source:
    id: PlatformUsername
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Users\IApplicationRoleConnection.cs
    startLine: 43
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the username on the platform a bot has connected.
  remarks: The length of the platform username must be max. 100 characters.
  example: []
  syntax:
    content: string? PlatformUsername { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property PlatformUsername As String
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformUsername*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.Metadata
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.Metadata
  id: Metadata
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection
  langs:
  - csharp
  - vb
  name: Metadata
  nameWithType: IApplicationRoleConnection.Metadata
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.Metadata
  type: Property
  source:
    id: Metadata
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Users\IApplicationRoleConnection.cs
    startLine: 50
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: >-
    Gets the object mapping of <xref href="Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnectionMetadata.Key" data-throw-if-not-resolved="false"></xref> to their stringified value

    for the user on the platform a bot has connected.
  remarks: The length of the stringified value must max. 100 characters.
  example: []
  syntax:
    content: IReadOnlyDictionary<string, string> Metadata { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IReadOnlyDictionary{System.String,System.String}
    content.vb: ReadOnly Property Metadata As IReadOnlyDictionary(Of String, String)
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.Metadata*
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformName*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformName
  href: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.html#Remora_Discord_API_Abstractions_Objects_IApplicationRoleConnection_PlatformName
  name: PlatformName
  nameWithType: IApplicationRoleConnection.PlatformName
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformUsername*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformUsername
  href: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.html#Remora_Discord_API_Abstractions_Objects_IApplicationRoleConnection_PlatformUsername
  name: PlatformUsername
  nameWithType: IApplicationRoleConnection.PlatformUsername
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.PlatformUsername
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnectionMetadata.Key
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnectionMetadata.Key
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnectionMetadata
  href: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnectionMetadata.html#Remora_Discord_API_Abstractions_Objects_IApplicationRoleConnectionMetadata_Key
  name: Key
  nameWithType: IApplicationRoleConnectionMetadata.Key
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnectionMetadata.Key
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.Metadata*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.Metadata
  href: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.html#Remora_Discord_API_Abstractions_Objects_IApplicationRoleConnection_Metadata
  name: Metadata
  nameWithType: IApplicationRoleConnection.Metadata
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnection.Metadata
- uid: System.Collections.Generic.IReadOnlyDictionary{System.String,System.String}
  commentId: T:System.Collections.Generic.IReadOnlyDictionary{System.String,System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyDictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  name: IReadOnlyDictionary<string, string>
  nameWithType: IReadOnlyDictionary<string, string>
  fullName: System.Collections.Generic.IReadOnlyDictionary<string, string>
  nameWithType.vb: IReadOnlyDictionary(Of String, String)
  fullName.vb: System.Collections.Generic.IReadOnlyDictionary(Of String, String)
  name.vb: IReadOnlyDictionary(Of String, String)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyDictionary`2
    name: IReadOnlyDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyDictionary`2
    name: IReadOnlyDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnectionMetadata
  commentId: T:Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnectionMetadata
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnectionMetadata.html
  name: IApplicationRoleConnectionMetadata
  nameWithType: IApplicationRoleConnectionMetadata
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationRoleConnectionMetadata
- uid: System.Collections.Generic.IReadOnlyDictionary`2
  commentId: T:System.Collections.Generic.IReadOnlyDictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  name: IReadOnlyDictionary<TKey, TValue>
  nameWithType: IReadOnlyDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>
  nameWithType.vb: IReadOnlyDictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.IReadOnlyDictionary(Of TKey, TValue)
  name.vb: IReadOnlyDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyDictionary`2
    name: IReadOnlyDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyDictionary`2
    name: IReadOnlyDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
