### YamlMime:ManagedReference
items:
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters
  commentId: T:Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters
  id: IApplicationInstallParameters
  parent: Remora.Discord.API.Abstractions.Objects
  children:
  - Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Permissions
  - Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Scopes
  langs:
  - csharp
  - vb
  name: IApplicationInstallParameters
  nameWithType: IApplicationInstallParameters
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters
  type: Interface
  source:
    id: IApplicationInstallParameters
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\IApplicationInstallParameters.cs
    startLine: 30
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Represents a set of parameters applied to custom application installation.
  example: []
  syntax:
    content: >-
      [PublicAPI]

      public interface IApplicationInstallParameters
    content.vb: >-
      <PublicAPI>

      Public Interface IApplicationInstallParameters
  attributes:
  - type: JetBrains.Annotations.PublicAPIAttribute
    ctor: JetBrains.Annotations.PublicAPIAttribute.#ctor
    arguments: []
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Scopes
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Scopes
  id: Scopes
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters
  langs:
  - csharp
  - vb
  name: Scopes
  nameWithType: IApplicationInstallParameters.Scopes
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Scopes
  type: Property
  source:
    id: Scopes
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\IApplicationInstallParameters.cs
    startLine: 36
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the OAuth2 scopes to add the application to the server with.
  example: []
  syntax:
    content: IReadOnlyList<string> Scopes { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IReadOnlyList{System.String}
    content.vb: ReadOnly Property Scopes As IReadOnlyList(Of String)
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Scopes*
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Permissions
  commentId: P:Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Permissions
  id: Permissions
  parent: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters
  langs:
  - csharp
  - vb
  name: Permissions
  nameWithType: IApplicationInstallParameters.Permissions
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Permissions
  type: Property
  source:
    id: Permissions
    path: D:\Projects\apps\Remora\documentation\src\Remora.Discord\Backend\Remora.Discord.API.Abstractions\API\Objects\Applications\IApplicationInstallParameters.cs
    startLine: 41
  assemblies:
  - Remora.Discord.API.Abstractions
  namespace: Remora.Discord.API.Abstractions.Objects
  summary: Gets the permissions to request for the created bot role.
  example: []
  syntax:
    content: IDiscordPermissionSet Permissions { get; }
    parameters: []
    return:
      type: Remora.Discord.API.Abstractions.Objects.IDiscordPermissionSet
    content.vb: ReadOnly Property Permissions As IDiscordPermissionSet
  overload: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Permissions*
references:
- uid: Remora.Discord.API.Abstractions.Objects
  commentId: N:Remora.Discord.API.Abstractions.Objects
  href: Remora.html
  name: Remora.Discord.API.Abstractions.Objects
  nameWithType: Remora.Discord.API.Abstractions.Objects
  fullName: Remora.Discord.API.Abstractions.Objects
  spec.csharp:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
  spec.vb:
  - uid: Remora
    name: Remora
    href: Remora.html
  - name: .
  - uid: Remora.Discord
    name: Discord
    href: Remora.Discord.html
  - name: .
  - uid: Remora.Discord.API
    name: API
    href: Remora.Discord.API.html
  - name: .
  - uid: Remora.Discord.API.Abstractions
    name: Abstractions
    href: Remora.Discord.API.Abstractions.html
  - name: .
  - uid: Remora.Discord.API.Abstractions.Objects
    name: Objects
    href: Remora.Discord.API.Abstractions.Objects.html
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Scopes*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Scopes
  href: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.html#Remora_Discord_API_Abstractions_Objects_IApplicationInstallParameters_Scopes
  name: Scopes
  nameWithType: IApplicationInstallParameters.Scopes
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Scopes
- uid: System.Collections.Generic.IReadOnlyList{System.String}
  commentId: T:System.Collections.Generic.IReadOnlyList{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyList`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<string>
  nameWithType: IReadOnlyList<string>
  fullName: System.Collections.Generic.IReadOnlyList<string>
  nameWithType.vb: IReadOnlyList(Of String)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of String)
  name.vb: IReadOnlyList(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Collections.Generic.IReadOnlyList`1
  commentId: T:System.Collections.Generic.IReadOnlyList`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<T>
  nameWithType: IReadOnlyList<T>
  fullName: System.Collections.Generic.IReadOnlyList<T>
  nameWithType.vb: IReadOnlyList(Of T)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of T)
  name.vb: IReadOnlyList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Permissions*
  commentId: Overload:Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Permissions
  href: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.html#Remora_Discord_API_Abstractions_Objects_IApplicationInstallParameters_Permissions
  name: Permissions
  nameWithType: IApplicationInstallParameters.Permissions
  fullName: Remora.Discord.API.Abstractions.Objects.IApplicationInstallParameters.Permissions
- uid: Remora.Discord.API.Abstractions.Objects.IDiscordPermissionSet
  commentId: T:Remora.Discord.API.Abstractions.Objects.IDiscordPermissionSet
  parent: Remora.Discord.API.Abstractions.Objects
  href: Remora.Discord.API.Abstractions.Objects.IDiscordPermissionSet.html
  name: IDiscordPermissionSet
  nameWithType: IDiscordPermissionSet
  fullName: Remora.Discord.API.Abstractions.Objects.IDiscordPermissionSet
